apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  namespace: ticketing
data:
  APP_NAME: "NordOps Ticketing Service"
  LOG_LEVEL: "INFO"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ticketing"
