apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-app
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-app
  template:
    metadata:
      labels:
        app: ticketing-app
    spec:
      containers:
        - name: ticketing-app
          image: nordops-ticketing:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "NordOps Ticketing Service"
            - name: LOG_LEVEL
              value: "INFO"
            - name: DATABASE_URL
              value: "postgresql+psycopg2://postgres:postgres@postgres:5432/ticketing"
